### PR TITLE
#9 Update contents by adding more fields and ordering it

### PR DESCRIPTION
**Pull request by Cleop**
#9 Update contents by adding more fields and ordering it

Open to suggestions @iteles @nelsonic regarding reordering although I think there are some things that could fit in multiple places so... within reason!

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
@Cleop LGTM! 🎉

**Review by iteles — APPROVED** [review]
@Cleop I did a little merge conflict resolution so I could merge this in, but because there were newer PRs that were merged in before this one (https://github.com/dwyl/product-owner-guide/pull/40), I think the latest commit could do with your keen eye to make sure I haven't deleted anything erroneously before merging please!

**Comment by Cleop** [comment]
@iteles - the last section had got lost in the merge so I've added that in. I've also done a scan and fixed any broken links / looked for typos etc. It should now be ready to go!

**Comment by iteles** [comment]
Argh, I was very careful to NOT delete that section because I was aware of #40 ! Thanks for spotting that 👍

**Pull request merged**
